auto:    true

brigade:
    name: Code for Summit County
    city:   "Summit County, Ohio"
    meetup-link: "http://www.meetup.com/Code-for-Summit-County/"
    google-group: "https://groups.google.com/d/forum/code-for-summit-county"
    github: "https://github.com/codeforsummitcounty"
    idea-list: "https://cfsc.hackpad.com/uE84hfRApzx"

content:
    title: Code for Summit County
    meetup-invite: "http://www.meetup.com/Code-for-Summit-County/"
    contact: "persa@codeforsummitcounty.org"
    banner: ./images/banner.jpg
    projects:
      - name: SummitWiki.org
        content: "<a href='http://summitwiki.org'>SummitWiki.org</a>"
    footer: "Thanks to Virginia Beach CfA and Seattle CfA for site templates" 

google-analytics:
    use: true
    code: UA-39250227-1
